
mapping allloca=([
"扬州城":({"/d/city/","beidajie1","beidajie2","beimen","bingyin",	
               "guangchang","houyuan","hxyanhui","kedian","kedian2",
               "kedian3","library","lichunyuan","lichunyuan2","meigui",
               "mishi","ml1","ml2","ml3","ml4","ml5","ml6","ml7",
               "mudan","nandajie1","nandajie2","nanmen","neizhai",
               "pomiao","postoffice","qianzhuang","shuyuan","shuyuan2",
               "tyroad2","work","wudang","wumiao","xidajie1","xidajie2",
               "ximen","xiting","xixiang","xxci1","xxci2","xxci3",
               "yamen","yaopu","yaopuls","ymzhengting","zahuopu","zhengting",
               "zuixianlou","zuixianlou2","zxlpath",
             }),
    "北京城":({"/d/city2/","alley1","alley2","alley3","andao1","andao10",
               "andao2","andao3","andao4","andao5","andao6","andao7","andao8",
               "andao9","anding","aobai1","aobai10","aobai11","aobai12","aobai2",
               "aobai3","aobai4","aobai5","aobai6","aobai7","aobai8","aobai9",
               "bingqiku","bingyin1","bingyin2","bridge","bridge2","bridge3","ceting",
               "chaguan","chaoyan1","chaoyan2","chaoyang","dangpu","datiepu","dating",
               "daxiao","daxiao2","di_an1","di_an2","di_an3","di_an4","di_anmen",
               "dongcha1","dongcha2","dongchangdamen","dongmen","duchang","duchang2",
               "duchang3","duchang4","eproom","fotang","guancai1","guancai2","haigang",
               "hbridge","houtai","huayuan","huichunt","jiulou1","jiulou2","kang1",
               "kang2","kang3","kedian","kedian1","kedian2","kedian3","kedian4",
               "lab","library","lilishi","mapeng","mianguan","nandaj1","nandaj2","neishi",
               "neitang","nproom","qianzhua","qishi","road1","road10","road2","road3",
               "road4","road5","road6","road7","road8","road9","shaizi-room","shufang",
               "shuyuan","shuyuan2","sproom","stage","tian_anm","tingyu","tuzai","wangfu1",
               "wangfu2","wangfu3","wenmiao","wproom","wuchang","wuqiku","xiaotan","xiaoyuan",
               "xichang1","xichang2","xichangdamen","xidan","xidan1","ximen","ximenwai",
               "xisi","xisi2","xiyuan","yihongyu","yongding","zahuopu","zhengmen","zhuang1",
               "zhuang2","zhuang3","zhuang4","zhuang5","zhuang6","zhuang7","zhuang8","zhuang9",
               "zhulin1","zhulin2","zhulin3","zhulin4","zhulin5",
                }),
    "白驼山":({"/d/baituo/","bridge","cao1","cao2","caomeide","caoping","cave","cave1","cedong",
               "chaifang","changlang","chufang","damen","datiepu","dating","dongjie",
               "dongkou","dongnei","fang","fende","gebi","guangchang","houmen","houyuan",
               "huayuan","jiudian","liangong","menlang","midao","mumen","neishi","nongshe",
               "restroom","room1","room2","room3","shanlu","shanlu1","shijie","shulin",
               "shulin1","storeroom","tuyuan","wuqiku","xiaolu1","xiaolu2","xiaolu3",
               "xiaolu4","xijie","ximen","yaofang","yuanzi","zhailuo","zhulin","zhuyuan",
                }),
    "灵蹴宫":({"/d/lingjiu/","biguan","caifeng","changl1","changl10","changl11",
               "changl12","changl13","changl14","changl15","changl2","changl3",
               "changl4","changl5","changl6","changl7","changl8","changl9","chufang",
               "daban","dadao1","dadao2","damen","dating","huayuan","jian","liangong",
               "men1","men2","men3","shanjiao","shufang","wuqiku","xianchou",
               "xiaodao1","xiaodao2",   

             }),
    "南阳":({"/d/nanyang/","duchuan","hanshui1","hanshui2","hong-damen","hong-zoulang",
             "hongniang-zhuang","hubudatang","kedian1","matou1","matou2","nanyang",
             "ruzhou","shanmen","shijie1","shijie2","shijie3","shijie4","shijie5",
             "shijie6","shijie7","wangxi-lu","xiaozheng","ximen","xingbudatang",
             "yamen-damen","yamen-datang","yidao","yidao2","yidao3","yingbin-lou1",
             
             }),
    "泉洲" :({"/d/quanzhou/","beimen","haigang","houyuan","huangye","jiaxing",
              "jxnanmen","laozhai","liang","midao","mishi","nanhu","nanhu1","nanmen",
              "qzroad1","qzroad2","qzroad3","qzroad4","qzroad5","tieqiang","well",
              "xijie","yanyu","yucun","zahuopu","zhongxin",
             }),

     ]);
          
               
                

   

